[project]
name = "ablit-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jaicenberg", email = "amencias99@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "gradio>=6.22.0",
    "huggingface-hub>=1.27.0",
    "mlx-lm>=0.31.3",
    "mlx-vlm>=0.6.10",
    "mlx-whisper>=0.4.3",
    "pillow>=12.3.0",
    "pypdf>=6.15.0",
]

[project.scripts]
ablit-ai = "ablit_ai:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
